baseurl = "/"
languageCode = "en-us"
title = "codicillus"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "jmetzel"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tutorials"
    url = "/tutorials/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

[params]
    description = "Thoughts on Data Analysis, Psychology and Society"
    footer = "&copy; [Julian M. Etzel](jme.netlify.com) 2018  <br> [Research Gate](https://researchgate.net) | [Twitter](https://twitter.com/julianetzel) | [GitHub](https://github.com/jmetzel)"
    disqusURL = "https://jme.netlify.com" 
    
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
